<WIP> change tabs to spaces in log_callback makefile
openenclave/openenclave pull request #3803
Opened 2021-01-15 02:09 UTC by BRMcLaren

This PR addresses an issue in the log_callback make file where tabs instead of spaces are used. This was not caught before because it depends on an environment variable that is never set in CI and is not the general use case.

Signed-off-by: brmclare <brmclare@microsoft.com>

2021-01-15 02:15 UTC, BRMcLaren commented
bors try

2021-01-15 02:18 UTC, mingweishih approved these changes
LGTM

2021-01-15 18:14 UTC, radhikaj approved these changes

2021-01-15 18:14 UTC, radhikaj commented
Thanks @BRMcLaren

2021-01-15 18:14 UTC, radhikaj commented
Bors r+

2021-01-15 23:42 UTC, mingweishih commented
bors r+

2021-01-15 23:44 UTC, BRMcLaren commented
bors r+

2021-01-16 04:20 UTC, mingweishih commented
bors r+

2021-01-18 18:59 UTC, CyanDevs commented
bors r+

2021-01-18 18:59 UTC, CyanDevs commented
bors try

2021-01-19 17:30 UTC, anakrish approved these changes

2021-01-19 17:34 UTC, anakrish requested changes
GNU Make requires TABs for recipe lines
https://www.gnu.org/software/make/manual/html_node/Rule-Syntax.html

TABS are part of the Makefile syntax.
Why is this reported as an error?

2021-01-19 18:02 UTC, CyanDevs commented
This change was done due to a new error we found:

> ‘recipe commences before first target. Stop.’
> This means the first thing in the makefile seems to be part of a recipe: it begins with a recipe prefix character and doesn’t appear to be a legal make directive (such as a variable assignment). Recipes must always be associated with a target.
Source: https://www.gnu.org/software/make/manual/html_node/Error-Messages.html

In current tests (non-prow) LVI_MITIGATION is not set anywhere (or possibly set to something other than ControlFlow), so the makefile will always evaluate ifeq ($(LVI_MITIGATION), ControlFlow) to false.

```
ifeq ($(LVI_MITIGATION), ControlFlow)
	ifeq ($(LVI_MITIGATION_BINDIR),)
		$(error LVI_MITIGATION_BINDIR is not set)
	endif
	# Only run once.
	ifeq (,$(findstring $(LVI_MITIGATION_BINDIR),$(CC)))
		CC := $(LVI_MITIGATION_BINDIR)/$(CC)
	endif
	COMPILER := $(COMPILER)-lvi-cfg
	CRYPTO_LDFLAGS := $(shell pkg-config oeenclave-$(COMPILER) --variable=${OE_CRYPTO_LIB}libslvicfg)
endif
```
Example: https://github.com/openenclave/openenclave/blob/5495755d436524ee425276acfb602d454720ac6a/samples/log_callback/enclave/Makefile#L8

In Prow/Jenkins, LVI_MITIGATION is set in the [Jenkins jobs (example)](https://github.com/openenclave/test-infra/blob/b79301462fc3540209e41964c0e5a12b5bb27218/config/jenkins/configuration/jobs/openenclave/Ubuntu1604DebugClang-7.yml#L49-L50), so the above will be true and run the block. Since the lines have a tab prefix, which would be read as a recipe prefix character, it expects it to be part of a target when it is actually not, and therefore fail with the error `‘recipe commences before first target. Stop.’`

2021-01-19 18:05 UTC, anakrish commented
@CyanDevs Thanks for the explanation!

2021-01-19 18:05 UTC, anakrish approved these changes

2021-01-19 22:59 UTC, mingweishih commented
bors r+

2021-01-20 01:57 UTC, mingweishih commented
bors r+

2021-01-20 23:20 UTC, BRMcLaren commented
bors r+

2021-01-21 11:05 UTC, BRMcLaren commented
bors r+

2021-01-21 11:07 UTC, BRMcLaren commented
bors r+

2021-01-21 23:59 UTC, merged