Fix compatibility issues between oeutil and oeverify
openenclave/openenclave pull request #4075
Opened 2021-06-07 16:10 UTC by ryanhsu19

Remove header information generated by `oe_get_evidence()` and pass the desired evidence format into `oe_verify_evidence()` in order to fix the compatibility issues between `oeutil` and `oeverify`.

Also, since evidence in `SGX_EPID_LINKABLE` or `SGX_EPID_UNLINKABLE` format can only be verified by Intel Attestation Service (IAS), modify `oeutil` and `oeverify` so that evidence in either EPID format will not be verified.

Signed-off-by: Ryan Hsu <ryhsu@microsoft.com>

2021-06-07 22:46 UTC, mingweishih approved these changes

2021-06-08 00:06 UTC, yentsanglee commented on tools/oeutil/enc/generate_evidence_enc.cpp
> +        &local_endorsements,
These 2 lines are intentional. Passing in non-null endorsement unnecessarily make calls to retrieve endorsements which can be time consuming. Please restore.

2021-06-08 00:13 UTC, yentsanglee commented
We want change host_verify sample too now that the evidence format is different.

2021-06-08 00:14 UTC, yentsanglee requested changes
We want change host_verify sample too now that the evidence format is different.

2021-06-08 02:48 UTC, dthaler approved these changes
Looks ok except for Yen's comment, which I agree with.  Once that is addressed it will look ok to me.

2021-06-08 03:54 UTC, yentsanglee approved these changes

2021-06-08 03:54 UTC, yentsanglee commented
bors try

2021-06-08 07:15 UTC, qiucwang commented
For oeutil/host/genereate_evidence.cpp, need to update `dump_oe_evidence()` as well.
After update, you can call `oeutil gen` with `--verbose` flag for verification.

2021-06-08 22:12 UTC, ryanhsu19 commented
bors try

2021-06-09 00:39 UTC, ryanhsu19 commented
bors try

2021-06-09 03:04 UTC, ryanhsu19 commented
bors try

2021-06-09 04:28 UTC, yentsanglee commented on tools/oeutil/host/generate_evidence.cpp
>      oe_result_t result = OE_UNEXPECTED;
Ignore formats that are not SGX_ECDSA.

2021-06-09 04:53 UTC, ryanhsu19 commented
bors try

2021-06-09 05:44 UTC, yentsanglee commented
bors r+

2021-06-09 06:51 UTC, merged