Fix attestation tool and sample
openenclave/openenclave pull request #4090
Opened 2021-06-11 02:02 UTC by ryanhsu19

These days we had a bug bash and found some bugs related to OE attestation. This PR is to

 - Update the usage and description of the `oeutil` tool because there is a typo and evidence in EPID formats cannot be properly generated (and we will look into the logic and functions in the future), and
 - Remove conversion errors due to OpenSSL utility in the `attested_tls` sample, with most of them being `-Wsign-conversion` and `-Wshorten-64-to-32` warnings treated as errors.

2021-06-11 03:39 UTC, yentsanglee approved these changes

2021-06-11 04:08 UTC, ryanhsu19 commented
bors try

2021-06-11 05:36 UTC, ryanhsu19 commented
bors try

2021-06-11 06:36 UTC, ryanhsu19 commented
Hmm, I am not sure what led to the failure of `cppException` unit test when the build type is `RelWithDebInfo`...

2021-06-11 16:37 UTC, mingweishih approved these changes

2021-06-11 16:42 UTC, mingweishih commented
@manojrupireddy please ch

> Hmm, I am not sure what led to the failure of `cppException` unit test on Windows when the build type is `RelWithDebInfo`...

cc @manojrupireddy

2021-06-11 19:46 UTC, qiucwang commented
I copied the branch and met some errors when I tried to build the sample with openssl lib.

Should be `bytes_read = SSL_read(ssl_session, buffer, len);`
https://github.com/openenclave/openenclave/blob/50e25f4999547b4e57bcadd9a20bb7f4cb686009/samples/attested_tls/common/openssl_utility.cpp#L214

Remove unused variable here.
https://github.com/openenclave/openenclave/blob/50e25f4999547b4e57bcadd9a20bb7f4cb686009/samples/attested_tls/client/enc/openssl_client.cpp#L102-L103

Should be `bytes_read = SSL_read(ssl, buf, len);`
https://github.com/openenclave/openenclave/blob/50e25f4999547b4e57bcadd9a20bb7f4cb686009/samples/attested_tls/client/enc/openssl_client.cpp#L60

Should be `while ((bytes_written = SSL_write(ssl, buf, len)) <= 0)`
https://github.com/openenclave/openenclave/blob/50e25f4999547b4e57bcadd9a20bb7f4cb686009/samples/attested_tls/client/enc/openssl_client.cpp#L42

2021-06-11 19:46 UTC, qiucwang requested changes
I copied the branch and met some errors when I tried to build the sample with openssl lib.

Should be `bytes_read = SSL_read(ssl_session, buffer, len);`
https://github.com/openenclave/openenclave/blob/50e25f4999547b4e57bcadd9a20bb7f4cb686009/samples/attested_tls/common/openssl_utility.cpp#L214

Remove unused variable here.
https://github.com/openenclave/openenclave/blob/50e25f4999547b4e57bcadd9a20bb7f4cb686009/samples/attested_tls/client/enc/openssl_client.cpp#L102-L103

Should be `bytes_read = SSL_read(ssl, buf, len);`
https://github.com/openenclave/openenclave/blob/50e25f4999547b4e57bcadd9a20bb7f4cb686009/samples/attested_tls/client/enc/openssl_client.cpp#L60

Should be `while ((bytes_written = SSL_write(ssl, buf, len)) <= 0)`
https://github.com/openenclave/openenclave/blob/50e25f4999547b4e57bcadd9a20bb7f4cb686009/samples/attested_tls/client/enc/openssl_client.cpp#L42

2021-06-11 19:50 UTC, CyanDevs commented
> Hmm, I am not sure what led to the failure of `cppException` unit test on Windows when the build type is `RelWithDebInfo`...

Hey @ryanhsu19 The `cppException` was an issue on CI that is now fixed. You're welcome to retry whenever you're ready and it should work. :)

2021-06-12 05:49 UTC, ryanhsu19 commented
> I copied the branch and met some errors when I tried to build the sample with openssl lib.
> 
> Should be `bytes_read = SSL_read(ssl_session, buffer, len);`
> https://github.com/openenclave/openenclave/blob/50e25f4999547b4e57bcadd9a20bb7f4cb686009/samples/attested_tls/common/openssl_utility.cpp#L214
> 
> Remove unused variables here.
> https://github.com/openenclave/openenclave/blob/50e25f4999547b4e57bcadd9a20bb7f4cb686009/samples/attested_tls/client/enc/openssl_client.cpp#L102-L103
> 
> Should be `bytes_read = SSL_read(ssl, buf, len);`
> https://github.com/openenclave/openenclave/blob/50e25f4999547b4e57bcadd9a20bb7f4cb686009/samples/attested_tls/client/enc/openssl_client.cpp#L60
> 
> Should be `while ((bytes_written = SSL_write(ssl, buf, len)) <= 0)`
> https://github.com/openenclave/openenclave/blob/50e25f4999547b4e57bcadd9a20bb7f4cb686009/samples/attested_tls/client/enc/openssl_client.cpp#L42

Thanks!

2021-06-12 06:07 UTC, ryanhsu19 commented
bors try

2021-06-12 06:56 UTC, ryanhsu19 commented
bors retry

2021-06-12 07:37 UTC, qiucwang approved these changes

2021-06-14 17:28 UTC, yentsanglee commented
bors r+

2021-06-14 18:26 UTC, merged