Support MONOTONIC, PROCESS_CPUTIME_ID, THREAD_CPUTIME_ID clocks
openenclave/openenclave pull request #4181
Opened 2021-07-21 15:28 UTC by anakrish

Signed-off-by: Anand Krishnamoorthi <anakrish@microsoft.com>

2021-07-21 15:29 UTC, anakrish commented
bors try

2021-07-21 18:55 UTC, dthaler requested changes
Please add test cases to the CI/CD.  (E.g., I think some of my comments are due to what looks like bugs, which would be easily caught by tests.)

2021-07-21 18:55 UTC, dthaler commented on enclave/core/time.c
> +#include "openenclave/bits/result.h"
why is this one out of alphabetical order?
Also lines 4 and 9 use quotes whereas the other lines use <> which seems inconsistent

2021-07-21 18:55 UTC, dthaler commented on host/linux/time.c
> +#include "openenclave/bits/time.h"
move down into alphabetical order and make all OE headers be consistent (I'd prefer all "" not <>)

2021-07-21 18:55 UTC, dthaler commented on host/linux/time.c
> +#include "openenclave/bits/types.h"
ditto

2021-07-21 18:55 UTC, dthaler commented on host/windows/time.c
> +                tp->tv_nsec = (total_time % 10000000) * 100;
Shouldn't these be set in the success case instead of the error case?

2021-07-21 18:55 UTC, dthaler commented on host/windows/time.c
> +                tp->tv_nsec = (total_time % 10000000) * 100;
Shouldn't these be set in the success case instead of the error case?

2021-07-21 18:55 UTC, dthaler commented on include/openenclave/internal/time.h
> + * oeedger8r generated declaration, there will be compile error.
```suggestion
 * an oeedger8r generated declaration, there will be a compile error.
```
grammar nit

2021-07-21 18:55 UTC, dthaler commented on syscall/syscall.c
> +//#include "syscall_t.h"
no commented out code

2022-06-27 18:27 UTC, radhikaj commented
Closing this for now. Please reopen when we resume working on it @anakrish

2022-06-27 18:27 UTC, closed without merging